version: '3.4'

services:
  deepstate_bot:
    restart: always
    image: otherwisejunk/thedeepstate
    depends_on:
     - deepstate_db
    environment:
     - DEEPSTATE=$DEEPSTATE
     - DATABASE=$DATABASE
  deepstate_db:
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=$SA_PASSWORD
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - /home/mssql/:/var/opt/mssql/
      - /var/opt/mssql/data
