name: .NET PR

on:
  pull_request:
    branches: [ main ]

env:
  AUTH0SCOPE: ${{secrets.Auth0Scope}}
  AUTH0CLIENTID: ${{secrets.Auth0ClientID}}
  AUTH0CLIENTSECRET: ${{secrets.Auth0ClientSecret}}
  AUTH0GRANTTYPE: ${{secrets.Auth0GrantType}}
  AUTH0AUDIENCE: ${{secrets.Auth0Audience}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TheDeepState.sln
    - name: Build
      run: dotnet build --no-restore TheDeepState.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal TheDeepState.sln
    - name: Build Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        tags: otherwisejunk/thedeepstate


